name: Build README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build-readme:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set node to v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci # installs packages with a clean slate (ci refers to continuous integration)

      - name: Generate profile card
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Generate README file
        run: node index.js
        env:
          GOODREADS_KEY: ${{secrets.GOODREADS_KEY}}
          GOODREADS_USER_ID: ${{secrets.GOODREADS_USER_ID}}
          LOCATION_LAT: ${{secrets.LOCATION_LAT}}
          LOCATION_LON: ${{secrets.LOCATION_LON}}
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
          STEAM_ID: ${{secrets.STEAM_ID}}
          STEAM_KEY: ${{secrets.STEAM_KEY}}

      - name: Push newly-generated README file
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' #optional defaults to master
